version: '3.8'

services:
  backend:
    build: backend
    volumes:
      - ./backend/:/home/web/app
    ports:
      - 4000:5000

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    env_file:
      - config.local
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations/:/docker-entrypoint-initdb.d


volumes:
  db_data:
    name: mysql-data

